<package format="3">
  <name>cmdvel_to_pwm</name>
  <version>0.0.1</version>
  <description>Convert cmd_vel to PWM</description>
  <maintainer email="your@email.com">jdamr</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
