<?xml version="1.0"?>
<package format="3">
  <name>trash_camera</name>
  <version>0.0.1</version>
  <description>YOLO + ToF 기반 쓰레기 감지 카메라 노드</description>
  <maintainer email="you@example.com">jdamr</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
